### ISSUE TITLE
Retry (TypeError: __init__() got an unexpected keyword argument 'other'

### ISSUE THREAD

**Issue by s-ahuja** [BennyThadikaran/Kite-Trader#2]
```
        retries = Retry(
            total=None,
            connect=3,
            read=3,
            redirect=0,
            status=3,
            other=0, <----- Line that gives the error
            backoff_factor=0.1,
            status_forcelist=[502, 503, 504],
            raise_on_status=False,
        )
```

**Error**
retries = Retry(
TypeError: __init__() got an unexpected keyword argument 'other'

Looks like the urllib3's Retry class has changed. is there a particular version of urllib3 that is needed?

**Comment by BennyThadikaran** [comment]
Use a virtual environment to isolate and prevent dependency conflicts. You perhaps have a different version of urlib3 installed and used by another application.

See [Create and Use Virtual Environments](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#create-and-use-virtual-environments)
