### ISSUE TITLE
how to get MIS or intraday margin value of a stock ?

### ISSUE THREAD

**Issue by hemangjoshi37a** [BennyThadikaran/Kite-Trader#5]
suppose i want to buy any stock for intraday then the amount i need to pay is around divided by 5 or whatever margin is decided for that stock by zerodha is , for most it is around 5 times but it is different for different stocks , please suggest me how to get this value ?

**Comment by BennyThadikaran** [comment]
You need to check with Zerodha support about this. There used to be a margins file you could download though i am not sure anymore.

Regards,
Benny Thadikaran
